apiVersion: v1
kind: Service
metadata:
    name: "bootcampmaster-56cb"
    labels:
        app: "bootcampmaster-56cb"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "bootcampmaster-56cb"